import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // We are defining a single sidebar for the entire book
  bookSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS 2 & Robotics Foundations',
      link: {
        type: 'generated-index',
        title: 'Module 1: ROS 2 & Robotics Foundations',
        description: 'Start your journey into the world of robotics with ROS 2.',
        slug: '/module-1'
      },
      items: [{type: 'autogenerated', dirName: 'module-1-ros-foundations'}],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Unity Digital Twin Simulation',
      link: {
        type: 'generated-index',
        title: 'Module 2: Gazebo & Unity Digital Twin Simulation',
        description: 'Learn how to simulate robots in virtual environments.',
        slug: '/module-2'
      },
      items: [{type: 'autogenerated', dirName: 'module-2-simulation'}],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac & Advanced Perception',
      link: {
        type: 'generated-index',
        title: 'Module 3: NVIDIA Isaac & Advanced Perception',
        description: 'Dive into advanced simulation and perception with NVIDIA\'s powerful tools.',
        slug: '/module-3'
      },
      items: [{type: 'autogenerated', dirName: 'module-3-nvidia-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) Pipelines',
      link: {
        type: 'generated-index',
        title: 'Module 4: Vision-Language-Action (VLA) Pipelines',
        description: 'Explore the cutting-edge of AI in robotics.',
        slug: '/module-4'
      },
      items: [{type: 'autogenerated', dirName: 'module-4-vla-pipelines'}],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      link: {
        type: 'generated-index',
        title: 'Capstone Project',
        description: 'Build an autonomous humanoid robot pipeline from scratch.',
        slug: '/capstone-project'
      },
      items: [{type: 'autogenerated', dirName: 'capstone-project'}],
    },
  ],
};

export default sidebars;
